Demo: GrabMultipleCamera.cpp
	g++ -g -o GrabMultipleCamera GrabMultipleCamera.cpp -I../../../include -Wl,-rpath=../../../lib/64 -L../../../lib/64 -lMvCameraControl -lpthread
	

clean:
	rm GrabMultipleCamera -rf
