Demo: Trigger_ImageCallback.cpp
	g++ -g -o Trigger_ImageCallback Trigger_ImageCallback.cpp -I../../../include -Wl,-rpath=../../../lib/64 -L../../../lib/64 -lMvCameraControl -lpthread
	

clean:
	rm Trigger_ImageCallback -rf
