Demo: GrabMultipleCamera.cpp
	g++ -g -o GrabMultipleCamera GrabMultipleCamera.cpp -I../../../include -Wl,-rpath=../../../lib/32 -L../../../lib/32 -lMvCameraControl -lpthread 
	

clean:
	rm GrabMultipleCamera -rf
