Demo: Grab_ImageCallback.cpp
	g++ -g -o Grab_ImageCallback Grab_ImageCallback.cpp -I../../../include -Wl,-rpath=../../../lib/32 -L../../../lib/32 -lMvCameraControl
	

clean:
	rm Grab_ImageCallback -rf
